# Generated by Django 6.0.4 on 2026-06-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('relationship', models.CharField(choices=[('wife', 'Wife'), ('father', 'Father'), ('mother', 'Mother'), ('stage_chairman', 'Stage Chairman'), ('defence', 'Defence'), ('lc1', 'LC1 Chairman'), ('landlord', 'Landlord')], db_index=True, max_length=50)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'is_active'], name='contacts_em_rider_i_454a0c_idx'), models.Index(fields=['phone_number'], name='contacts_em_phone_n_191040_idx'), models.Index(fields=['relationship'], name='contacts_em_relatio_0d1642_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('rider',), name='unique_primary_emergency_contact_per_rider')],
            },
        ),
    ]
