# Generated by Django 6.0.4 on 2026-06-16 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('speed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('heading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('detected_violation', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='riders.guestrider')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['rider', 'recorded_at'], name='location_ri_rider_i_df0d3d_idx'), models.Index(fields=['guest_rider', 'recorded_at'], name='location_ri_guest_r_14007e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('out_of_stage', 'Out of Stage'), ('unknown_area', 'Unknown Area'), ('speed_violation', 'Speed Violation'), ('no_movement', 'No Movement'), ('guest_rider_hotspot', 'Guest Rider Hotspot')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('auto_fine_triggered', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riders.guestrider')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='location_su_event_t_ef78db_idx'), models.Index(fields=['auto_fine_triggered'], name='location_su_auto_fi_db271a_idx')],
            },
        ),
    ]
