# Generated by Django 6.0.4 on 2026-06-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('suspend', 'Suspend'), ('verification', 'Verification'), ('security_alert', 'Security Alert')], db_index=True, max_length=50)),
                ('entity', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='analytics_a_action_c1a4bb_idx'), models.Index(fields=['entity', 'entity_id'], name='analytics_a_entity_46b602_idx'), models.Index(fields=['timestamp'], name='analytics_a_timesta_184ff5_idx')],
            },
        ),
    ]
