# Generated by Django 6.0.4 on 2026-06-16 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='fines_finet_name_f7b402_idx'), models.Index(fields=['is_active'], name='fines_finet_is_acti_0d0595_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_type', models.CharField(choices=[('rider', 'Rider'), ('guest_rider', 'Guest Rider')], db_index=True, max_length=20)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='fines/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='riders.guestrider')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fines', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='riders.riderprofile')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='stages.stage')),
                ('fine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='fines.finetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='fines_fine_status_1fd55b_idx'), models.Index(fields=['offender_type', 'status'], name='fines_fine_offende_bf39c1_idx'), models.Index(fields=['stage', 'status'], name='fines_fine_stage_i_8319e3_idx'), models.Index(fields=['fine_type'], name='fines_fine_fine_ty_4417e5_idx'), models.Index(fields=['created_at'], name='fines_fine_created_ca84d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('guest_rider__isnull', True), ('offender_type', 'rider'), ('rider__isnull', False)), models.Q(('guest_rider__isnull', False), ('offender_type', 'guest_rider'), ('rider__isnull', True)), _connector='OR'), name='fine_offender_consistency')],
            },
        ),
    ]
