# Generated by Django 6.0.4 on 2026-06-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='adminpanel__level_a70cbe_idx'), models.Index(fields=['created_at'], name='adminpanel__created_2379b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('update_profile', 'Update Profile'), ('location_update', 'Location Update'), ('emergency_alert', 'Emergency Alert'), ('approved', 'Approved'), ('suspended', 'Suspended')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='riders.riderprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rider', 'action'], name='adminpanel__rider_i_c4e000_idx'), models.Index(fields=['action'], name='adminpanel__action_031eca_idx'), models.Index(fields=['timestamp'], name='adminpanel__timesta_4c9c3f_idx')],
            },
        ),
    ]
