# Generated by Django 6.0.4 on 2026-06-16 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('suspicious_login', 'Suspicious Login'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('location_violation', 'Location Violation'), ('account_takeover', 'Account Takeover'), ('fake_identity', 'Fake Identity'), ('general', 'General')], db_index=True, default='general', max_length=50)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('auto_flagged', models.BooleanField(db_index=True, default=False)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resolved'], name='security_se_user_id_f3cb00_idx'), models.Index(fields=['user', 'resolved', 'created_at'], name='security_se_user_id_30c879_idx'), models.Index(fields=['severity', 'resolved'], name='security_se_severit_d193c2_idx'), models.Index(fields=['alert_type'], name='security_se_alert_t_95c5e2_idx'), models.Index(fields=['created_at'], name='security_se_created_c5082c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('resolved', False), models.Q(('resolved', True), ('resolved_by__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='security_alert_resolution_integrity')],
            },
        ),
    ]
