# Generated by Django 6.0.4 on 2026-06-09 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('district', models.CharField(db_index=True, max_length=255)),
                ('division', models.CharField(db_index=True, max_length=255)),
                ('parish', models.CharField(db_index=True, max_length=255)),
                ('village', models.CharField(db_index=True, max_length=255)),
                ('chairman_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('secretary_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('defense_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_registered_riders', models.PositiveIntegerField(default=0)),
                ('total_guest_riders_seen', models.PositiveIntegerField(default=0)),
                ('suspicious_activity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman', models.ForeignKey(blank=True, limit_choices_to={'role': 'stage_chairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_stages', to=settings.AUTH_USER_MODEL)),
                ('defense', models.ForeignKey(blank=True, limit_choices_to={'role': 'stage_defense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_stages', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(blank=True, limit_choices_to={'role': 'stage_secretary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='stages_stag_name_625878_idx'), models.Index(fields=['district'], name='stages_stag_distric_36f5bf_idx'), models.Index(fields=['division'], name='stages_stag_divisio_a5a208_idx'), models.Index(fields=['is_active'], name='stages_stag_is_acti_56102f_idx')],
            },
        ),
    ]
