# Generated by Django 6.0.4 on 2026-06-16 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('death', 'Death'), ('meeting', 'Meeting'), ('security', 'Security'), ('admin_change', 'Administration Change'), ('general', 'General')], db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['announcement_type'], name='announcemen_announc_d6756a_idx'), models.Index(fields=['is_active'], name='announcemen_is_acti_a26055_idx'), models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Condolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('burial_location', models.CharField(max_length=255)),
                ('date_of_death', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('stage_chairman', 'Stage Chairman'), ('stage_secretary', 'Stage Secretary'), ('stage_defense', 'Stage Defense'), ('rider', 'Rider'), ('guest_rider', 'Guest Rider')], db_index=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_condolences', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolences', to='riders.riderprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_condolences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='announcemen_status_b72663_idx'), models.Index(fields=['date_of_death'], name='announcemen_date_of_27f702_idx'), models.Index(fields=['target_role'], name='announcemen_target__e08c1b_idx')],
            },
        ),
    ]
