# Generated by Django 6.0.4 on 2026-06-09 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='riders/profile/')),
                ('national_id_photo', models.ImageField(blank=True, null=True, upload_to='riders/national_ids/')),
                ('bike_plate_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Plate must contain uppercase letters and numbers only', regex='^[A-Z0-9]+$')])),
                ('national_id_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('rider_phone_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('suspicious_activity_score', models.IntegerField(default=0)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='stages.stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=255)),
                ('village_name', models.CharField(max_length=255)),
                ('landlord_name', models.CharField(max_length=255)),
                ('landlord_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('father_name', models.CharField(max_length=255)),
                ('father_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('wife_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wife_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='riders.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_plate_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Plate must contain uppercase letters and numbers only', regex='^[A-Z0-9]+$')])),
                ('national_id_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +2567XXXXXXXX', regex='^\\+256[0-9]{9}$')])),
                ('current_area', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('blacklisted', 'Blacklisted')], db_index=True, default='active', max_length=20)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suspicious_activity_score', models.IntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='riders_gues_status_0ea829_idx'), models.Index(fields=['current_area'], name='riders_gues_current_056c97_idx'), models.Index(fields=['latitude', 'longitude'], name='riders_gues_latitud_7fc838_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['status'], name='riders_ride_status_fc215b_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['stage'], name='riders_ride_stage_i_4d7891_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_online'], name='riders_ride_is_onli_038f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_available'], name='riders_ride_is_avai_68ac83_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='riders_ride_latitud_43d8a3_idx'),
        ),
    ]
